/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ufrpe.poo.cardapio.gui;

import br.ufrpe.poo.cardapio.dados.RepositorioProdutosArray;
import br.ufrpe.poo.cardapio.neo.Fachada;
import br.ufrpe.poo.cardapio.neo.Produtos;
import java.awt.Color;
import java.util.ArrayList;


/**
 *
 * @author Endryo
 */
public class CardapioMenu extends javax.swing.JFrame {
    
    Fachada fachada = new Fachada();
    RepositorioProdutosArray rep;
    ArrayList<Produtos> carrinho;
    ArrayList<Produtos> itens = new ArrayList<>();
    /**
     * Creates new form CardapioMenu
     */
    public CardapioMenu() {
        this.rep = new RepositorioProdutosArray();
        initComponents();
        rep.add(); //Inicia os objetos do repositorio
        jTesteCombo.setSelectedItem(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanelPainel = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelMesa = new javax.swing.JLabel();
        jTextFieldMesa = new javax.swing.JTextField();
        jLabelObs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObs = new javax.swing.JTextArea();
        jButtonFinalizarPedido = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jLabelValorTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCarrinho = new javax.swing.JTable();
        jButtonDecrementa = new javax.swing.JButton();
        jButtonIncrementa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAddCarrinho = new javax.swing.JButton();
        jTesteCombo = new javax.swing.JComboBox<>();
        jButtonLimparCarrinho = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jLabelQuantosItens = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setText("Cardapio - nome fantasia");

        jLabelCliente.setText("Cliente:");

        jLabelMesa.setText("Mesa:");

        jLabelObs.setText("Observações:");

        jTextAreaObs.setColumns(20);
        jTextAreaObs.setForeground(java.awt.Color.lightGray);
        jTextAreaObs.setRows(5);
        jTextAreaObs.setText("Escreva aqui as observações do seu pedido...");
        jTextAreaObs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAreaObsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaObs);

        jButtonFinalizarPedido.setText("Finalizar Pedido");
        jButtonFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarPedidoActionPerformed(evt);
            }
        });

        jLabelTotal.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabelTotal.setText("Total:");

        jLabelValorTotal.setText("R$ 0.0");

        jTableCarrinho.setAutoCreateRowSorter(true);
        jTableCarrinho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Preço", "Observação", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableCarrinho);

        jButtonDecrementa.setText("-");
        jButtonDecrementa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDecrementaMouseClicked(evt);
            }
        });

        jButtonIncrementa.setText("+");
        jButtonIncrementa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIncrementaMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Menu");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Carrinho");

        jButtonAddCarrinho.setText("Adicionar ao carrinho");
        jButtonAddCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddCarrinhoMouseClicked(evt);
            }
        });

        jTesteCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calabresa R$ 25", "Mussarela R$ 22", "4Queijos R$ 20", "Tradicional R$ 7", "X-Bacon R$ 8", "X-Tudo R$ 9", "Coca R$ 8", "Soda R$ 7", "Água R$ 2" }));

        jButtonLimparCarrinho.setText("Limpar Carrinho");
        jButtonLimparCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimparCarrinhoMouseClicked(evt);
            }
        });

        jButtonDeletar.setText("Deletar Item");
        jButtonDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeletarMouseClicked(evt);
            }
        });

        jLabelQuantosItens.setText("0 Produtos no Carrinho");

        javax.swing.GroupLayout jPanelPainelLayout = new javax.swing.GroupLayout(jPanelPainel);
        jPanelPainel.setLayout(jPanelPainelLayout);
        jPanelPainelLayout.setHorizontalGroup(
            jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPainelLayout.createSequentialGroup()
                .addGroup(jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPainelLayout.createSequentialGroup()
                        .addGroup(jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPainelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jLabelObs)
                                        .addGroup(jPanelPainelLayout.createSequentialGroup()
                                            .addGap(127, 127, 127)
                                            .addComponent(jLabelTitulo))
                                        .addGroup(jPanelPainelLayout.createSequentialGroup()
                                            .addComponent(jLabelCliente)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabelMesa)
                                            .addGap(3, 3, 3)
                                            .addComponent(jButtonDecrementa)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButtonIncrementa))
                                        .addGroup(jPanelPainelLayout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTesteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelPainelLayout.createSequentialGroup()
                                        .addGap(173, 173, 173)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPainelLayout.createSequentialGroup()
                                            .addComponent(jLabelTotal)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabelValorTotal)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelQuantosItens))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPainelLayout.createSequentialGroup()
                                            .addComponent(jButtonFinalizarPedido)
                                            .addGap(30, 30, 30)
                                            .addComponent(jButtonDeletar)
                                            .addGap(27, 27, 27)
                                            .addComponent(jButtonLimparCarrinho)))))
                            .addGroup(jPanelPainelLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jButtonAddCarrinho)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelPainelLayout.setVerticalGroup(
            jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGroup(jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPainelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCliente)
                            .addComponent(jTextFieldMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDecrementa)
                            .addComponent(jButtonIncrementa)
                            .addComponent(jLabelMesa)))
                    .addGroup(jPanelPainelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTesteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(28, 28, 28)
                .addComponent(jLabelObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAddCarrinho)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jLabelValorTotal)
                    .addComponent(jLabelQuantosItens))
                .addGap(18, 18, 18)
                .addGroup(jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFinalizarPedido)
                    .addComponent(jButtonLimparCarrinho)
                    .addComponent(jButtonDeletar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanelPainel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonIncrementaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIncrementaMouseClicked
        // TODO add your handling code here:
        int mesa = Integer.parseInt(jTextFieldMesa.getText());
        jTextFieldMesa.setText(String.valueOf(fachada.incrementa(mesa)));
    }//GEN-LAST:event_jButtonIncrementaMouseClicked

    private void jButtonDecrementaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDecrementaMouseClicked
        // TODO add your handling code here:
        int mesa = Integer.parseInt(jTextFieldMesa.getText());
        jTextFieldMesa.setText(String.valueOf(fachada.decrementa(mesa)));
    }//GEN-LAST:event_jButtonDecrementaMouseClicked

    private void jTextAreaObsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaObsMouseClicked
        // TODO add your handling code here:
        fachada.resetObs(jTextAreaObs);   
    }//GEN-LAST:event_jTextAreaObsMouseClicked

    private void jButtonFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarPedidoActionPerformed
        // TODO add your handling code here: 
        fachada.entradaException(jTextFieldNome.getText(), jTextFieldMesa.getText(), jLabelValorTotal.getText());    
    }//GEN-LAST:event_jButtonFinalizarPedidoActionPerformed

    private void jButtonAddCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddCarrinhoMouseClicked
        // TODO add your handling code here:
        fachada.addCarrinho(rep, carrinho, itens, jTableCarrinho, jLabelValorTotal,jTesteCombo, jTextAreaObs, jLabelQuantosItens);      
    }//GEN-LAST:event_jButtonAddCarrinhoMouseClicked

    private void jButtonLimparCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimparCarrinhoMouseClicked
        // TODO add your handling code here:    
        fachada.limparCarrinho(itens,jTableCarrinho, jLabelValorTotal, jLabelQuantosItens);
    }//GEN-LAST:event_jButtonLimparCarrinhoMouseClicked

    private void jButtonDeletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeletarMouseClicked
        // TODO add your handling code here:
        fachada.deleteItem(itens, jTableCarrinho, jLabelValorTotal, jLabelQuantosItens);
    }//GEN-LAST:event_jButtonDeletarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardapioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardapioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardapioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardapioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardapioMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCarrinho;
    private javax.swing.JButton jButtonDecrementa;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonFinalizarPedido;
    private javax.swing.JButton jButtonIncrementa;
    private javax.swing.JButton jButtonLimparCarrinho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelMesa;
    private javax.swing.JLabel jLabelObs;
    private javax.swing.JLabel jLabelQuantosItens;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JPanel jPanelPainel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableCarrinho;
    private javax.swing.JComboBox<String> jTesteCombo;
    private javax.swing.JTextArea jTextAreaObs;
    private javax.swing.JTextField jTextFieldMesa;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
